### PR TITLE
UI: change Settings window width/height

### PR DESCRIPTION
**Pull request by SuslikV**
makes interface window 4:3 and slightly smaller for better appearance.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
This is outside the scope of my original pull request. I specifically did not change any of the default window sizes on purpose, I only allowed the window to be made smaller to accommodate smaller screen sizes. You are welcome to make your own PR against jp9000/master for this, but I will not be including it with mine.

**Comment by SuslikV** [comment]
When I run OBS Studio on the 1024x768 display, the taskbar of the Windows swallows OK|Cancel|Apply buttons of the Settings window. So, it is possible to resize the window, but you need to do it each time manually. That's why I'm pending to include this in your PR directly. Please, review it again.

Disadvantages:
Right after this, the changes to the warning message placement of the _Settings>Advanced_ needed to be done. Because it should be visible, always. And no matter how you resize the window (manually or it done automatically). I think it is better to place the warning message right under the Video section (between "advancedVideoContainer" and "advAudioGroupBox" QGroupBox - similar to all other warnings - right under the option that rises the warning itself).

**Comment by Fenrirthviti** [comment]
The disadvantages you point out are the exact reason I am not changing the default window size. This is itself a workaround to allow smaller screen sizes (which are increasingly less common) to be able to access the entire settings window. Broader changes to accommodate an ancient 1024x768 display will not be added by me. Make your own PR.

**Comment by SuslikV** [comment]
OK. I'll try.

**Pull request closed without merging**
